// Generated by npm run catalog.
window.MODEL_CATALOG = [
  {
    "id": "01-heart-reference",
    "title": "心脏 · Blender 单图参考",
    "type": "glb",
    "description": "外部结构研究模型。GLB 材质与 Blender 完整渲染可能不同；原始建模工程另行保留。",
    "parts": [
      "models/01-heart-reference/model.glb"
    ],
    "bytes": 5710512,
    "images": [
      "models/01-heart-reference/heart_anterior.png",
      "models/01-heart-reference/heart_three_quarter.png"
    ]
  },
  {
    "id": "02-heart-multiview",
    "title": "心脏 · Blender 四视图参考",
    "type": "glb",
    "description": "外部结构研究模型。GLB 材质与 Blender 完整渲染可能不同；原始建模工程另行保留。",
    "parts": [
      "models/02-heart-multiview/model.glb"
    ],
    "bytes": 26853044,
    "images": [
      "models/02-heart-multiview/heart_anterior.png",
      "models/02-heart-multiview/heart_four_views.png"
    ]
  },
  {
    "id": "03-heart-anatomy-reviewed",
    "title": "心脏 · Blender 解剖修订",
    "type": "glb",
    "description": "外部结构研究模型。GLB 材质与 Blender 完整渲染可能不同；原始建模工程另行保留。",
    "parts": [
      "models/03-heart-anatomy-reviewed/model.glb.part001",
      "models/03-heart-anatomy-reviewed/model.glb.part002"
    ],
    "bytes": 96543864,
    "images": [
      "models/03-heart-anatomy-reviewed/heart_anterior.png",
      "models/03-heart-anatomy-reviewed/heart_four_views.png"
    ]
  },
  {
    "id": "04-heart-surface-polished",
    "title": "心脏 · Blender 表面材质优化",
    "type": "glb",
    "description": "外部结构研究模型。GLB 材质与 Blender 完整渲染可能不同；原始建模工程另行保留。",
    "parts": [
      "models/04-heart-surface-polished/model.glb.part001",
      "models/04-heart-surface-polished/model.glb.part002"
    ],
    "bytes": 83099500,
    "images": [
      "models/04-heart-surface-polished/heart_anterior.png",
      "models/04-heart-surface-polished/heart_four_views.png"
    ]
  },
  {
    "id": "05-heart-reference-matched",
    "title": "心脏 · Blender 参考图拟合（当前外观版）",
    "type": "glb",
    "description": "外部结构研究模型。GLB 材质与 Blender 完整渲染可能不同；原始建模工程另行保留。",
    "parts": [
      "models/05-heart-reference-matched/model.glb.part001",
      "models/05-heart-reference-matched/model.glb.part002",
      "models/05-heart-reference-matched/model.glb.part003"
    ],
    "bytes": 125488932,
    "images": [
      "models/05-heart-reference-matched/heart_anterior.png",
      "models/05-heart-reference-matched/heart_four_views.png"
    ]
  },
  {
    "id": "history-heart-anatomy-01",
    "title": "历史渲染 · 程序化心脏 · anatomy-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-01/front.png",
      "models/history-heart-anatomy-01/left.png",
      "models/history-heart-anatomy-01/rear.png",
      "models/history-heart-anatomy-01/right.png",
      "models/history-heart-anatomy-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-anatomy-02",
    "title": "历史渲染 · 程序化心脏 · anatomy-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-02/front.png",
      "models/history-heart-anatomy-02/left.png",
      "models/history-heart-anatomy-02/rear.png",
      "models/history-heart-anatomy-02/right.png",
      "models/history-heart-anatomy-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-anatomy-03",
    "title": "历史渲染 · 程序化心脏 · anatomy-03",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-03/front.png",
      "models/history-heart-anatomy-03/left.png",
      "models/history-heart-anatomy-03/rear.png",
      "models/history-heart-anatomy-03/right.png",
      "models/history-heart-anatomy-03/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-anatomy-04",
    "title": "历史渲染 · 程序化心脏 · anatomy-04",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-04/front.png",
      "models/history-heart-anatomy-04/left.png",
      "models/history-heart-anatomy-04/rear.png",
      "models/history-heart-anatomy-04/right.png",
      "models/history-heart-anatomy-04/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-anatomy-05",
    "title": "历史渲染 · 程序化心脏 · anatomy-05",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-05/front.png",
      "models/history-heart-anatomy-05/left.png",
      "models/history-heart-anatomy-05/rear.png",
      "models/history-heart-anatomy-05/right.png",
      "models/history-heart-anatomy-05/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-anatomy-06",
    "title": "历史渲染 · 程序化心脏 · anatomy-06",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-anatomy-06/front.png",
      "models/history-heart-anatomy-06/left.png",
      "models/history-heart-anatomy-06/rear.png",
      "models/history-heart-anatomy-06/right.png",
      "models/history-heart-anatomy-06/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-baseline",
    "title": "历史渲染 · 程序化心脏 · baseline",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-baseline/front.png",
      "models/history-heart-baseline/left.png",
      "models/history-heart-baseline/rear.png",
      "models/history-heart-baseline/right.png",
      "models/history-heart-baseline/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-blockout-01",
    "title": "历史渲染 · 程序化心脏 · blockout-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-blockout-01/front.png",
      "models/history-heart-blockout-01/left.png",
      "models/history-heart-blockout-01/rear.png",
      "models/history-heart-blockout-01/right.png",
      "models/history-heart-blockout-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-blockout-02",
    "title": "历史渲染 · 程序化心脏 · blockout-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-blockout-02/front.png",
      "models/history-heart-blockout-02/left.png",
      "models/history-heart-blockout-02/rear.png",
      "models/history-heart-blockout-02/right.png",
      "models/history-heart-blockout-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-blockout-03",
    "title": "历史渲染 · 程序化心脏 · blockout-03",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-blockout-03/front.png",
      "models/history-heart-blockout-03/left.png",
      "models/history-heart-blockout-03/rear.png",
      "models/history-heart-blockout-03/right.png",
      "models/history-heart-blockout-03/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-final-candidate",
    "title": "历史渲染 · 程序化心脏 · final-candidate",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-final-candidate/front.png",
      "models/history-heart-final-candidate/left.png",
      "models/history-heart-final-candidate/rear.png",
      "models/history-heart-final-candidate/right.png",
      "models/history-heart-final-candidate/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-material-01",
    "title": "历史渲染 · 程序化心脏 · material-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-material-01/front.png",
      "models/history-heart-material-01/left.png",
      "models/history-heart-material-01/rear.png",
      "models/history-heart-material-01/right.png",
      "models/history-heart-material-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-material-02",
    "title": "历史渲染 · 程序化心脏 · material-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-material-02/front.png",
      "models/history-heart-material-02/left.png",
      "models/history-heart-material-02/rear.png",
      "models/history-heart-material-02/right.png",
      "models/history-heart-material-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-material-baseline-02",
    "title": "历史渲染 · 程序化心脏 · material-baseline-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-material-baseline-02/front.png",
      "models/history-heart-material-baseline-02/left.png",
      "models/history-heart-material-baseline-02/rear.png",
      "models/history-heart-material-baseline-02/right.png",
      "models/history-heart-material-baseline-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-material-final",
    "title": "历史渲染 · 程序化心脏 · material-final",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-material-final/front.png",
      "models/history-heart-material-final/left.png",
      "models/history-heart-material-final/rear.png",
      "models/history-heart-material-final/right.png",
      "models/history-heart-material-final/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-epicardium-01",
    "title": "历史渲染 · 程序化心脏 · reference-epicardium-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-epicardium-01/front.png",
      "models/history-heart-reference-epicardium-01/left.png",
      "models/history-heart-reference-epicardium-01/rear.png",
      "models/history-heart-reference-epicardium-01/right.png",
      "models/history-heart-reference-epicardium-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-epicardium-02",
    "title": "历史渲染 · 程序化心脏 · reference-epicardium-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-epicardium-02/front.png",
      "models/history-heart-reference-epicardium-02/left.png",
      "models/history-heart-reference-epicardium-02/rear.png",
      "models/history-heart-reference-epicardium-02/right.png",
      "models/history-heart-reference-epicardium-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-epicardium-03",
    "title": "历史渲染 · 程序化心脏 · reference-epicardium-03",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-epicardium-03/front.png",
      "models/history-heart-reference-epicardium-03/left.png",
      "models/history-heart-reference-epicardium-03/rear.png",
      "models/history-heart-reference-epicardium-03/right.png",
      "models/history-heart-reference-epicardium-03/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-final",
    "title": "历史渲染 · 程序化心脏 · reference-final",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-final/front.png",
      "models/history-heart-reference-final/left.png",
      "models/history-heart-reference-final/rear.png",
      "models/history-heart-reference-final/right.png",
      "models/history-heart-reference-final/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-final-02",
    "title": "历史渲染 · 程序化心脏 · reference-final-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-final-02/front.png",
      "models/history-heart-reference-final-02/left.png",
      "models/history-heart-reference-final-02/rear.png",
      "models/history-heart-reference-final-02/right.png",
      "models/history-heart-reference-final-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-final-03",
    "title": "历史渲染 · 程序化心脏 · reference-final-03",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-final-03/front.png",
      "models/history-heart-reference-final-03/left.png",
      "models/history-heart-reference-final-03/rear.png",
      "models/history-heart-reference-final-03/right.png",
      "models/history-heart-reference-final-03/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-refined-01",
    "title": "历史渲染 · 程序化心脏 · reference-refined-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-refined-01/front.png",
      "models/history-heart-reference-refined-01/left.png",
      "models/history-heart-reference-refined-01/rear.png",
      "models/history-heart-reference-refined-01/right.png",
      "models/history-heart-reference-refined-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-shape-01",
    "title": "历史渲染 · 程序化心脏 · reference-shape-01",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-shape-01/front.png",
      "models/history-heart-reference-shape-01/left.png",
      "models/history-heart-reference-shape-01/rear.png",
      "models/history-heart-reference-shape-01/right.png",
      "models/history-heart-reference-shape-01/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-reference-shape-02",
    "title": "历史渲染 · 程序化心脏 · reference-shape-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-reference-shape-02/front.png",
      "models/history-heart-reference-shape-02/left.png",
      "models/history-heart-reference-shape-02/rear.png",
      "models/history-heart-reference-shape-02/right.png",
      "models/history-heart-reference-shape-02/threeQuarter.png"
    ]
  },
  {
    "id": "history-heart-verified-02",
    "title": "历史渲染 · 程序化心脏 · verified-02",
    "type": "images",
    "description": "已保存的阶段渲染，仅展示图片；可交互最终模型见程序化心脏入口。",
    "images": [
      "models/history-heart-verified-02/front.png",
      "models/history-heart-verified-02/left.png",
      "models/history-heart-verified-02/rear.png",
      "models/history-heart-verified-02/right.png",
      "models/history-heart-verified-02/threeQuarter.png"
    ]
  },
  {
    "id": "web-heart-multiview",
    "title": "程序化心脏·多视图最终版",
    "type": "web",
    "description": "基于四视图参考的程序化 Three.js 心脏查看器；当前最终证据为 reference-final-03。",
    "src": "models/web-heart-multiview/index.html",
    "images": []
  },
  {
    "id": "web-heart-reference",
    "title": "程序化心脏·单图参考版",
    "type": "web",
    "description": "基于单张正面参考图的程序化 Three.js 心脏查看器。",
    "src": "models/web-heart-reference/index.html",
    "images": []
  },
  {
    "id": "web-human-atlas",
    "title": "Human Atlas",
    "type": "web",
    "description": "可交互人体解剖查看器；源数据来自 BodyParts3D，需保留 CC BY 4.0 署名。",
    "src": "models/web-human-atlas/index.html",
    "images": []
  },
  {
    "id": "web-mitochondrion",
    "title": "线粒体剖面程序化模型",
    "type": "web",
    "description": "程序化 Three.js 线粒体剖面模型，包含外膜、内膜、嵴和基质颗粒。",
    "src": "models/web-mitochondrion/index.html",
    "images": []
  }
];
