import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const records = [];
for (const dir of (await readdir(path.join(root, 'models'), { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
  if (!dir.isDirectory()) continue;
  const folder = path.join(root, 'models', dir.name);
  let entry;
  try { entry = JSON.parse(await readFile(path.join(folder, 'entry.json'), 'utf8')); }
  catch (error) { throw new Error(`${dir.name}/entry.json: ${error.message}`); }
  if (!entry.title || !['glb', 'web', 'images'].includes(entry.type)) throw new Error(`Invalid entry: ${dir.name}`);
  async function asset(relative) {
    if (typeof relative !== 'string' || !relative || relative.includes('\\') || relative.split('/').includes('..') || path.isAbsolute(relative) || /^[a-z]+:/i.test(relative)) throw new Error(`Unsafe asset path: ${relative}`);
    const file = path.join(folder, relative);
    if (!(await stat(file)).isFile()) throw new Error(`Missing asset: ${file}`);
    return ['models', dir.name, ...relative.split('/')].map(encodeURIComponent).join('/');
  }
  const record = { id: dir.name, title: entry.title, type: entry.type, description: entry.description || '' };
  if (entry.type === 'glb') {
    const files = entry.parts || [entry.src];
    if (!files.length) throw new Error(`Empty model: ${dir.name}`);
    record.parts = await Promise.all(files.map(asset));
    record.bytes = (await Promise.all(files.map((file) => stat(path.join(folder, file))))).reduce((sum, info) => sum + info.size, 0);
    const first = await readFile(path.join(folder, files[0]));
    if (first.length < 12 || first.toString('ascii', 0, 4) !== 'glTF' || first.readUInt32LE(4) !== 2 || first.readUInt32LE(8) !== record.bytes) throw new Error(`Invalid GLB length/header: ${dir.name}`);
  } else if (entry.type === 'web') record.src = await asset(entry.src);
  record.images = await Promise.all((entry.images || []).map(asset));
  if (entry.type === 'images' && !record.images.length) throw new Error(`No images: ${dir.name}`);
  records.push(record);
}
const output = `// Generated by npm run catalog.\nwindow.MODEL_CATALOG = ${JSON.stringify(records, null, 2)};\n`;
const target = path.join(root, 'catalog.js');
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== output) throw new Error('Catalog is stale: run npm run catalog');
} else await writeFile(target, output);
console.log(`Validated ${records.length} entries.`);
